### ISSUE TITLE
Error uploading

### ISSUE THREAD

**Issue by jpmurray** [cwhite92/b2-sdk-php#2]
Hello,

Trying to upload like so 
````
$file = $client->upload([
            'BucketId' => $bucketId,
            'BucketName' => $bucketName,
            'FileName' => $filename,
            'Body' => $file2Send
        ]);
```
 results in this exception: `Received error from B2: error reading uploaded data`.

I tought it was on their end, so I emailed them but it seems that they're throwing the ball back at us, so I tought I should post it to see if it was of any help! :)

> Did you ensure that you have a vaild upload token?

> If the HTTP return status is anything other than 200, the caller must not upload to this URL again. Instead the caller MUST call b2_get_upload_url to get a new uploadUrl and new authorizationToken. The reason for this is that the individual storage pod you are uploading into may be full of data and thus will never accept any more data for now, or it has crashed, or has been placed into maintenance and will not accept data, etc. No matter what the reason, you must use b2_get_upload_url to get a new uploadUrl and new authorizationToken in order to retry the upload.

**Comment by cwhite92** [comment]
Could you let me know what the `$file2Send` variable contains? It sounds to me like it's a path to a file, when it needs to be the string content of a file or a file resource (from fopen).

**Comment by jpmurray** [comment]
Here it is ;-)

```

stream resource {@408
  wrapper_type: "plainfile"
  stream_type: "STDIO"
  mode: "r"
  unread_bytes: 0
  seekable: true
  uri: "/home/vagrant/Code/podcaster/storage/app/rec/Testing-un-deux2016-02-161455661745.mp3"
  timed_out: false
  blocked: true
  eof: false
  options: []
}
```

**Comment by jpmurray** [comment]
Out of nothing, I just created a test.txt file and tried to send it... And it was successfully uploaded :confused:

**Comment by cwhite92** [comment]
Super weird. If you could condense your code down into a snippet that reproduces the problem I would have a much better chance of figuring it out. I just tried a variety of uploads myself and they all worked fine. :/

**Comment by jpmurray** [comment]
It's really simple actually, I call it from an artisan command, so this is the code that is in the `handle()` function.

```
        $accountId=env('B2_ACCOUNT_ID', null);
        $applicationId=env('B2_APPLICATION_KEY', null);
        $bucketId=env('B2_BUCKET_ID', null);
        $bucketName="name";
        $filename = $this->argument('filename');
        $path2file = storage_path()."/app/rec/".$filename;
        $file2Send = fopen($path2file, 'r');

        $client = new Client($accountId, $applicationId);
        $this->comment("Trying to send file ".$filename);
        
        $file = $client->upload([
            'BucketId' => $bucketId,
            'BucketName' => $bucketName,
            'FileName' => $filename,
            'Body' => $file2Send
        ]);

        $this->comment("Done! File ID:  ".$file->getId());
```

So yeah, the txt file gets me to the comment with a fild ID, so is a PDF file I just tried.

I re-tried the same MP3, got the error. So I went on and found another MP3 file, and it won't work either. (Also tried, just for fun, to rename the mp3 file so it has a txt entension, but of course it won't change a thing). At this point, I'm thinking it's either the file format or the filesize that causes the problem?

The script take some time to error out, so it feels like the file is being sent somehow.

**Comment by jpmurray** [comment]
It's a long shot, because I would think I'd see another error, but maybe the transaction takes too long, something time out?

**Comment by cwhite92** [comment]
Ok, super weird. The client passes off the responsibility of determining the file content type to B2 (which they specifically allow according to their docs ([see here](https://github.com/cwhite92/b2-sdk-php/blob/master/src/Client.php#L201))) and I'm wondering if that's what is causing the issue.

You can override that content type by specifying a `FileContentType` key to the options array. Could you try setting that to `audio/mpeg` and see if the upload is successful? As you said, it works on other file types and the files do seem to be getting sent as you're getting a response back from B2.

Also I'm on holiday this weekend with just a Chromebook and very slow internet so apologies if I take a bit to get back :D

**Comment by jpmurray** [comment]
Hey, no worries, take your time! ;-)

So, no, it didn't work. BUT.

I cheated on you and tried an upload using [this class](https://github.com/Savjee/php-backblaze-b2-uploader) and it worked perfectly!

I didn't take the time to check what is different, I'll let that to you since you know your code better (unless you ask for it, I'll take the time :P), but yeah, that one works :/

**Comment by jpmurray** [comment]
GOT IT.

I don't know why it worked on some and not on the MP3, but I was missing a `fread()` before sending it to your class! So the above code snippet, for it to work, is now:
```
$accountId=env('B2_ACCOUNT_ID', null);
        $applicationId=env('B2_APPLICATION_KEY', null);
        $bucketId=env('B2_BUCKET_ID', null);
        $bucketName="name";
        $filename = $this->argument('filename');
        $path2file = storage_path()."/app/rec/".$filename;
        $file2Send = fopen($path2file, 'r');
        $read_file = fread($file2Send,filesize($path2file));

        $client = new Client($accountId, $applicationId);
        $this->comment("Trying to send file ".$filename);

        $file = $client->upload([
            'BucketId' => $bucketId,
            'BucketName' => $bucketName,
            'FileName' => $filename,
            'Body' => $read_file,
        ]);

        $this->comment("Done! File ID:  ".$file->getId());
```

**Comment by cwhite92** [comment]
Hey @jpmurray,

Really sorry for not being on the ball about this issue, I'm looking after a sick relative right now so I haven't had a lot of time at all.

I've just pushed and tagged a fix which (for me, anyway) seems to fix the problem. Could you perhaps update to 1.0.1 and tell me if your issue is fixed?

Cheers!

**Comment by cwhite92** [comment]
Haven't heard anything about this issue for a while and the problem seems to be fixed from what I can see.

Closing this for now but if you're still having issues feel free to comment. :)

**Comment by jpmurray** [comment]
Weirdly enough, I still get the same behaviour! Error reading from uploaded file unless I do a fread before sending the file. 

(Honestly, I'm starting to think there is a configuration problem somewhere on my setup and not your scripts...)

**Comment by GerhardLiebenberg** [comment]
I had the same issue.

Got it working after repeating jpmurry's (fopen & fread).

Maybe it is because my file is first stored on my server (in session) as part of an object.
I guess curl_setopt() does not want an object or the path to a file that is still under the session's control. It needs the file itself and that is why fread() does the job.

Thanx for this.
